name: Auto Commit Bot

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at 12 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Set Up Git Identity
        run: |
          git config --global user.email "saiyamkumar2007@gmail.com"
          git config --global user.name "saiyam0211"

      - name: Run Auto Commit Script
        run: python auto_commit.py

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "saiyamkumar2007@gmail.com"
          git config --global user.name "saiyam0211"
          git remote set-url origin https://saiyam0211:${GH_TOKEN}@github.com/saiyam0211/bengaluru_ai.git
          git pull origin master
          git add .
          git commit -m "Automated commit by GitHub Actions" || echo "No changes to commit"
          git push origin master
